/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banco.View;

import banco.Dao.Clientes;
import banco.DAO.connectDAO;

/**
 *
 * @author Alunos
 */
public class CadastroClientes extends javax.swing.JFrame {

    /**
     * Creates new form CadastroClientes
     */
    public CadastroClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1_id = new javax.swing.JLabel();
        jLabel2_nome = new javax.swing.JLabel();
        jLabel3_endereco = new javax.swing.JLabel();
        jLabel4_numero = new javax.swing.JLabel();
        jLabel5_complemento = new javax.swing.JLabel();
        jLabel6_bairro = new javax.swing.JLabel();
        jLabel7_cidade = new javax.swing.JLabel();
        jLabel8_uf = new javax.swing.JLabel();
        jLabel9_cep = new javax.swing.JLabel();
        jLabel10_fone = new javax.swing.JLabel();
        jLabel11_cpf = new javax.swing.JLabel();
        jLabel12_cnpj = new javax.swing.JLabel();
        jLabel13_data = new javax.swing.JLabel();
        jTextField1_id = new javax.swing.JTextField();
        jTextField2_nome = new javax.swing.JTextField();
        jTextField3_endereco = new javax.swing.JTextField();
        jTextField4_numero = new javax.swing.JTextField();
        jTextField5_complemento = new javax.swing.JTextField();
        jTextField6_bairro = new javax.swing.JTextField();
        jTextField7_cidade = new javax.swing.JTextField();
        jTextField8_UF = new javax.swing.JTextField();
        jTextField9_cep = new javax.swing.JTextField();
        jTextField10_fone = new javax.swing.JTextField();
        jTextField11_cpf = new javax.swing.JTextField();
        jTextField12_data = new javax.swing.JTextField();
        jTextField13_cnpj = new javax.swing.JTextField();
        jButton1_cadastro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        jLabel1_id.setText("ID");

        jLabel2_nome.setText("Nome");

        jLabel3_endereco.setText("Endereço");

        jLabel4_numero.setText("Número");

        jLabel5_complemento.setText("Complemento");

        jLabel6_bairro.setText("Bairro");

        jLabel7_cidade.setText("Cidade");

        jLabel8_uf.setText("UF");

        jLabel9_cep.setText("CEP");

        jLabel10_fone.setText("Fone");

        jLabel11_cpf.setText("CPF");

        jLabel12_cnpj.setText("CNPJ");

        jLabel13_data.setText("Data Nascimento");

        jButton1_cadastro.setText("Cadastrar");
        jButton1_cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_cadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3_endereco)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField3_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9_cep)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField9_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5_complemento)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField5_complemento)
                                        .addGap(7, 7, 7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel4_numero)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField4_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1_id)
                                .addGap(34, 34, 34)
                                .addComponent(jTextField1_id, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jLabel2_nome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField2_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6_bairro)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField6_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel8_uf)
                                        .addGap(21, 21, 21)
                                        .addComponent(jTextField8_UF, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7_cidade)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField7_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10_fone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField10_fone, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13_data)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField12_data, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1_cadastro)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12_cnpj)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField13_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel11_cpf)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField11_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(32, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1_id)
                    .addComponent(jTextField1_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2_nome)
                    .addComponent(jTextField2_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3_endereco)
                    .addComponent(jTextField3_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4_numero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField5_complemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5_complemento))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField6_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7_cidade)
                            .addComponent(jTextField7_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel6_bairro)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField9_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9_cep))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField8_UF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8_uf)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10_fone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10_fone)
                    .addComponent(jLabel13_data, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField12_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField13_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11_cpf)
                        .addComponent(jTextField11_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12_cnpj))
                .addGap(18, 18, 18)
                .addComponent(jButton1_cadastro)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_cadastroActionPerformed
    Clientes dados = new Clientes();
    dados.setIdCli(Integer.parseInt(jTextField1_id.getText()));
    dados.setNomeCli(jTextField2_nome.getText());
    dados.setEndeCli(jTextField3_endereco.getText());
    dados.setNumeCli(jTextField4_numero.getText());
    dados.setComplCli(jTextField5_complemento.getText());
    dados.setBairCli(jTextField6_bairro.getText());
    dados.setCidaCli(jTextField7_cidade.getText());
    dados.setUfCli(jTextField8_UF.getText());
    dados.setCepCli(jTextField9_cep.getText());
    dados.setFoneCli(jTextField10_fone.getText());
    dados.setCpfCli(jTextField11_cpf.getText());
    dados.setCnpjCli(jTextField13_cnpj.getText());
    }//GEN-LAST:event_jButton1_cadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_cadastro;
    private javax.swing.JLabel jLabel10_fone;
    private javax.swing.JLabel jLabel11_cpf;
    private javax.swing.JLabel jLabel12_cnpj;
    private javax.swing.JLabel jLabel13_data;
    private javax.swing.JLabel jLabel1_id;
    private javax.swing.JLabel jLabel2_nome;
    private javax.swing.JLabel jLabel3_endereco;
    private javax.swing.JLabel jLabel4_numero;
    private javax.swing.JLabel jLabel5_complemento;
    private javax.swing.JLabel jLabel6_bairro;
    private javax.swing.JLabel jLabel7_cidade;
    private javax.swing.JLabel jLabel8_uf;
    private javax.swing.JLabel jLabel9_cep;
    private javax.swing.JTextField jTextField10_fone;
    private javax.swing.JTextField jTextField11_cpf;
    private javax.swing.JTextField jTextField12_data;
    private javax.swing.JTextField jTextField13_cnpj;
    private javax.swing.JTextField jTextField1_id;
    private javax.swing.JTextField jTextField2_nome;
    private javax.swing.JTextField jTextField3_endereco;
    private javax.swing.JTextField jTextField4_numero;
    private javax.swing.JTextField jTextField5_complemento;
    private javax.swing.JTextField jTextField6_bairro;
    private javax.swing.JTextField jTextField7_cidade;
    private javax.swing.JTextField jTextField8_UF;
    private javax.swing.JTextField jTextField9_cep;
    // End of variables declaration//GEN-END:variables
}
